---
engines:
  bundler-audit:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  flog:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "./ruby/blackjack/Gemfile.lock"
  - "./ruby/blackjack/**/*.rb"
exclude_paths:
- javascript/
- ruby/where
- ruby/blackjack/doc/
- ruby/blackjack/log/
- ruby/blackjack/spec/
