# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'awesome_print', require: false
  gem 'byebug'
  gem 'fuubar', require: false
  gem 'guard-rspec', require: false
  gem 'pry-byebug'
  gem 'rubocop', require: false
  gem 'ruby-lint', require: false
  gem 'warning', require: false
end
