# frozen_string_literal: true

filter(/\.md$/, /\.DS_Store/, /Rakefile/, /\.gemspec$/, /Gemfile.*$/, /bin/, /tmp/)

guard :rspec, cmd: :rspec do
  require 'guard/rspec/dsl'

  Guard::RSpec::Dsl.new(self).tap do |dsl|
    watch(dsl.rspec.spec_helper) { dsl.rspec.spec_dir }
    watch(dsl.rspec.spec_files)

    dsl.watch_spec_files_for(dsl.ruby.lib_files)
  end
end
