#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/where'
require 'awesome_print'

ap [].where.where

ap [{ x: 1 }, { x: 2 }, { x: 1 }].where(x: 1)

ap [{ foo: 'bar' }, { foo: 'barbaz' }, { foo: 'bazbar', bar: 'foo' }]
  .where(foo: /bar/)
  .where(bar: /.*/)
